[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
remappings = [
    "@openzeppelin-contracts/=dependencies/@openzeppelin-contracts-5.4.0/",
    "@uniswap-universal-router/=dependencies/@uniswap-universal-router-2.0.0/",
    "forge-std/=dependencies/forge-std-1.10.0/",
]

[soldeer]
remappings_version = false
remappings_location = "config"
remappings_regenerate = true

[dependencies]
forge-std = "1.10.0"
"@openzeppelin-contracts" = "5.4.0"
"@uniswap-universal-router" = "2.0.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
